config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :user do
    get '/sign_in', to: 'public/sessions#new'
  end

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  root to: 'homes#top'

  get '/' => 'homes#top'
  get '/about' => 'homes#about'
    
  resources :users,  only: [:show, :edit, :update] do
    get '/unsubscribe' => 'users#unsubscribe'
    patch '/withdrawal' => 'users#withdrawa'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end
 
  resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
    
    get 'searches/search' => "searches#search", as: 'search'
  
  namespace :admin do
    resource :owners,  only: [:show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence:true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :post_image
    belongs_to :user
    
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    validates :material, presence: true
    validates :body, presence: true
    validates :post_image, presence: false
    
    def get_post_image(width, height)
      unless post_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        post_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
      end
      post_image.variant(resize_to_limit: [width, height]).processed
    end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follow, class_name: "User"
    belongs_to :follower, class_name: "User"
    validates :follow, presence: true
    validates :follower, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name,presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,message: "は正しいフォーマットで入力してください" }, uniqueness: { message: "このアドレスは使用できません"}
  validates :profile_image, presence: false
  validates :password, presence: true, length: { minimum: 6 }
  
  # 退会済みはログイン不可
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  # 画像
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    
  private

    def after_sign_in_path_for(resource)
      if resource.is_a?(Admin)
        admin_owners_path
      else
        user_path(current_user)
      end
    end

    def after_sign_out_path_for(resource)
      case resource
      when :admin   # ログアウト時はシンボルが返ってくる
        new_admin_session_path
      when :user  # ログアウト時はシンボルが返ってくる
        new_user_session_path
      end
    end
    
    protected
      def configure_sign_up_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end
  
  def destroy
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def unsubscribe
  end

  def withdrawal
    @user = User.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email,:profile_image)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handmade.com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg", style="background-color:#afafb0;">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Handmade.com</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav my-2 my-md-0 mr-md-3">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "マイページ", user_path(current_user),class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link text-dark' %>
                </li>
              <% elsif admin_signed_in? %>
                <li>
                  <%= link_to "マイページ", admin_owners_path,class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' %>
                </li>
              <% else %>
                <li>
                  <%= link_to "About", about_path,class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path,class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path ,class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>